apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-west-2c
- us-west-2d
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
fargateProfiles:
- name: fp-default
  selectors:
  - namespace: default
  - namespace: kube-system
  status: ""
- name: fp-acs
  selectors:
  - namespace: alfresco
  status: ""  
iam:
  vpcResourceControllerPolicy: true
# https://eksctl.io/usage/iamserviceaccounts/  
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: alf-pod
      namespace: alfresco
    roleName: ore23-alf-pod
    attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
        Resource: 'arn:aws:s3:::ReplaceWithActualS3Bucket'
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    roleName: ore23-aws-alb
    wellKnownPolicies:
      awsLoadBalancerController: true

kind: ClusterConfig
kubernetesNetworkConfig:
  ipFamily: IPv4
metadata:
  name: ore23
  region: us-west-2
  version: "1.29"
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.138.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: HighlyAvailable
